VecaraSystem/Controllers/PagosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VecaraSystem.Data;
using VecaraSystem.Models;

namespace VecaraSystem.Controllers
{
    public class PagosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PagosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Pagos
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Pagos.Include(p => p.ControlAccesoId).Include(p => p.TipoPagoId);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Pagos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pagos = await _context.Pagos
                .Include(p => p.ControlAccesoId)
                .Include(p => p.TipoPagoId)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (pagos == null)
            {
                return NotFound();
            }

            return View(pagos);
        }

        // GET: Pagos/Create
        public IActionResult Create()
        {
            ViewData["IdControlAcceso"] = new SelectList(_context.ControlAcceso, "Id", "Id");
            ViewData["IdTipoPago"] = new SelectList(_context.TipoPagos, "Id", "Nombre");
            return View();
        }

        // POST: Pagos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,IdTipoPago,IdControlAcceso,Monto,Fecha")] Pagos pagos)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pagos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdControlAcceso"] = new SelectList(_context.ControlAcceso, "Id", "Id", pagos.IdControlAcceso);
            ViewData["IdTipoPago"] = new SelectList(_context.TipoPagos, "Id", "Nombre", pagos.IdTipoPago);
            return View(pagos);
        }

        // GET: Pagos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pagos = await _context.Pagos.SingleOrDefaultAsync(m => m.Id == id);
            if (pagos == null)
            {
                return NotFound();
            }
            ViewData["IdControlAcceso"] = new SelectList(_context.ControlAcceso, "Id", "Id", pagos.IdControlAcceso);
            ViewData["IdTipoPago"] = new SelectList(_context.TipoPagos, "Id", "Nombre", pagos.IdTipoPago);
            return View(pagos);
        }

        // POST: Pagos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,IdTipoPago,IdControlAcceso,Monto,Fecha")] Pagos pagos)
        {
            if (id != pagos.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pagos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PagosExists(pagos.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdControlAcceso"] = new SelectList(_context.ControlAcceso, "Id", "Id", pagos.IdControlAcceso);
            ViewData["IdTipoPago"] = new SelectList(_context.TipoPagos, "Id", "Nombre", pagos.IdTipoPago);
            return View(pagos);
        }

        // GET: Pagos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pagos = await _context.Pagos
                .Include(p => p.ControlAccesoId)
                .Include(p => p.TipoPagoId)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (pagos == null)
            {
                return NotFound();
            }

            return View(pagos);
        }

        // POST: Pagos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pagos = await _context.Pagos.SingleOrDefaultAsync(m => m.Id == id);
            _context.Pagos.Remove(pagos);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PagosExists(int id)
        {
            return _context.Pagos.Any(e => e.Id == id);
        }
    }
}

VecaraSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VecaraSystem</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">VecaraSystem</a>
            </div>
            <div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
					<li><a asp-area="" asp-controller="Empleados" asp-action="Index">Empleados</a></li>
					<li><a asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a></li>
					<li><a asp-area="" asp-controller="Vehiculos" asp-action="Index">Vehiculos</a></li>
					<li><a asp-area="" asp-controller="Marcas" asp-action="Index">Marcas</a></li>
					<li><a asp-area="" asp-controller="Modelos" asp-action="Index">Modelos</a></li>
					<li><a asp-area="" asp-controller="Parqueos" asp-action="Index">Parqueos</a></li>
					<li><a asp-area="" asp-controller="TipoParqueos" asp-action="Index">TipoParqueos</a></li>
					<li><a asp-area="" asp-controller="Pagos" asp-action="Index">Pagos</a></li>
					<li><a asp-area="" asp-controller="TipoPagos" asp-action="Index">TipoPagos</a></li>
					<li><a asp-area="" asp-controller="ControlAccesoes" asp-action="Index">Control Acceso</a></li>
					<li><a asp-area="" asp-controller="Roles" asp-action="ListaRoles">Roles</a></li>
					<li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
					<li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
				</ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - VecaraSystem</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>